config/routes.rb
Rails.application.routes.draw do
  resources :tanuki_sad_words
  root 'tanuki_pages#home'
  get 'tanuki_pages/home'
  
  get 'tanuki_pages/taanukiGladWords'
  get 'tanuki_pages/taanukiRecentlyWords'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tanuki_sad_word.rb
class TanukiSadWord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tanuki_pages_controller.rb
class TanukiPagesController < ApplicationController
  def home
  end
end

app/controllers/tanuki_sad_words_controller.rb
class TanukiSadWordsController < ApplicationController
  before_action :set_tanuki_sad_word, only: [:show, :edit, :update, :destroy]

  # GET /tanuki_sad_words
  # GET /tanuki_sad_words.json
  def index
    @tanuki_sad_words = TanukiSadWord.all
  end

  # GET /tanuki_sad_words/1
  # GET /tanuki_sad_words/1.json
  def show
  end

  # GET /tanuki_sad_words/new
  def new
    @tanuki_sad_word = TanukiSadWord.new
  end

  # GET /tanuki_sad_words/1/edit
  def edit
  end

  # POST /tanuki_sad_words
  # POST /tanuki_sad_words.json
  def create
    @tanuki_sad_word = TanukiSadWord.new(tanuki_sad_word_params)

    respond_to do |format|
      if @tanuki_sad_word.save
        format.html { redirect_to @tanuki_sad_word, notice: 'Tanuki sad word was successfully created.' }
        format.json { render :show, status: :created, location: @tanuki_sad_word }
      else
        format.html { render :new }
        format.json { render json: @tanuki_sad_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tanuki_sad_words/1
  # PATCH/PUT /tanuki_sad_words/1.json
  def update
    respond_to do |format|
      if @tanuki_sad_word.update(tanuki_sad_word_params)
        format.html { redirect_to @tanuki_sad_word, notice: 'Tanuki sad word was successfully updated.' }
        format.json { render :show, status: :ok, location: @tanuki_sad_word }
      else
        format.html { render :edit }
        format.json { render json: @tanuki_sad_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tanuki_sad_words/1
  # DELETE /tanuki_sad_words/1.json
  def destroy
    @tanuki_sad_word.destroy
    respond_to do |format|
      format.html { redirect_to tanuki_sad_words_url, notice: 'Tanuki sad word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tanuki_sad_word
      @tanuki_sad_word = TanukiSadWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tanuki_sad_word_params
      params.require(:tanuki_sad_word).permit(:sad_word, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tanuki_pages_helper.rb
module TanukiPagesHelper
end

app/helpers/tanuki_sad_words_helper.rb
module TanukiSadWordsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The TanukiApp
    by <a href="https://twitter.com/kobutodo">@kobutodo</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About/Contact",   'http://kobuyarou.fakefur.jp/kobupage/kobinfo/' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <a id="logo" href="<%= tanuki_pages_home_url %>">
    <img src=<%= asset_path "aicon-leaf.png" %> class="align-top" id="logo-image" alt="ぽじたぬ">
    <span style="padding-left:3px;">ぽじたぬ</span>
  </a>
  
  <nav>
    <ul id="logo-menu">
      <li><%= link_to "Home",   tanuki_pages_home_url %></li>
      <li><%= link_to "Log in", tanuki_sad_words_url %></li>
    </ul>
  </nav>
  
</header>

app/views/layouts/_tanuki_room.html.erb
  <h3>たぬきの小屋</h3>
  
  <ul class="nav nav-tabs">
    <li class="nav-item room-tab-item">
      <a class="nav-link room-tab-link active" href="<%= tanuki_sad_words_url %>"><img class="tanuki-image" src="<%= asset_path "tanuki_sad_a_tri.png" %>">なやみ</a>
    </li>
    <li class="nav-item room-tab-item">
      <a class="nav-link room-tab-link" href="<%= tanuki_sad_words_url %>"><img class="tanuki-image" src="<%= asset_path "tanuki_happy_a_tri.png" %>">はげまし</a>
    </li>
    <li class="nav-item room-tab-item">
      <a class="nav-link room-tab-link" style="padding-top: 20px;" href="<%= tanuki_sad_words_url %>"><img class="tanuki-image" src="<%= asset_path "aicon-foot.png" %>"></br>たぬき村</a>
    </li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TanukiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="page-top"></div>
    <div class="container-md">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/tanuki_pages/home.html.erb
<div class="title">
    
    <div class ="text-center">
        <h3>ぽじてぃぶ・たぬき β（開発中）</h3>
        <p><small>〜ポジティブなことばでたぬきを元気づけよう〜</small></p>
        <p>つかれたときそっとひらくと一息つけるサイトです。<br>投稿するにはTwitterとの連動が必要ですが、連動後は匿名での投稿も可能。</p>
    </div>
    
    <hr class="my-4">
    
    <h6>☆元気づけの例☆</h6>
    <div class="balloon">
        <table>
        <tr>
        <td style="vertical-align: top;"><img class="tanuki-image" border="0" src="<%= asset_path "tanuki_sad_a_tri.png" %>" alt="たぬき悲しみ"></td>
        <td><div class="sad-balloon">
            <span class="twi-link"><mark>@sad-tanuki</mark></span>
            <p class="tanu-word">つかれた…。山に帰りたい…。</p>
        </div></td>
        </tr>
        </table>
    </div>
    
    <div class="balloon">
        <table>
        <tr>
        <td style="vertical-align: top;"><img class="tanuki-image" border="0" src="<%= asset_path "tanuki_happy_a_tri.png" %>" alt="たぬき励まし"></td>
        <td><div class="glad-balloon">
            <span class="twi-link"><mark>@glad-tanuki</mark></span>
            <p class="tanu-word">まぁ元気だせや。いいこともあるで。</p>
        </div></td>
        </tr>
        </table>
    </div>
    
    <hr class="my-4">
    
    <div class ="text-center">
        <p>ログインして他のたぬきから元気づけてもらおう。</p>
        <a class="btn btn-primary btn-lg" href="<%= tanuki_sad_words_url %>" role="button"> Twitterでログイン</a>
    </div>
</div>
    
<div class ="sub-content">
    <h5><mark>最近のたぬきのことば</mark></h5>    
    <p>ここにポジティブな投稿を時間でソートして配置</p>
</div>

<div class ="sub-content">
    <h5><mark>たぬきの元気づけ</mark></h5>    
    <p>ここにかなしいことばとポジティブな言葉をセットでおく</p>
</div>

app/views/tanuki_sad_words/_form.html.erb
<%= form_with(model: tanuki_sad_word, local: true) do |form| %>
  <% if tanuki_sad_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tanuki_sad_word.errors.count, "error") %> prohibited this tanuki_sad_word from being saved:</h2>

      <ul>
        <% tanuki_sad_word.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sad_word %>
    <%= form.text_area :sad_word %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tanuki_sad_words/edit.html.erb
<h1>Editing Tanuki Sad Word</h1>

<%= render 'form', tanuki_sad_word: @tanuki_sad_word %>

<%= link_to 'Show', @tanuki_sad_word %> |
<%= link_to 'Back', tanuki_sad_words_path %>

app/views/tanuki_sad_words/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<div class="sub-content">

  <%= render 'layouts/tanuki_room' %>
  
  <h4>たぬきのなやみ</h4>
  <p>なやみを投稿してぽじてぃぶな言葉をかけてもらおう。じぶんにぽじてぃぶな言葉をかけるも良し。</p>
  <%= link_to 'なやむ', new_tanuki_sad_word_path, class: "btn" %>
  
  <hr class="my-4">
  
  <% if @tanuki_sad_words.count == 0 %>
    今のたぬきになやみはない！
  <% end %>
  
  <table>
    <tbody>
      
      <% @tanuki_sad_words.each do |tanuki_sad_word| %>
        <tr>
          <td><%= tanuki_sad_word.sad_word %></td>
          <td><%= tanuki_sad_word.user_id %></td>
          <td><%= link_to 'Show', tanuki_sad_word %></td>
          <td><%= link_to 'Edit', edit_tanuki_sad_word_path(tanuki_sad_word) %></td>
          <td><%= link_to 'Destroy', tanuki_sad_word, method: :delete, data: { confirm: '消してもよいですか?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <hr class="my-4">
</div>

app/views/tanuki_sad_words/new.html.erb
<h1>たぬきのなやみ</h1>
<p>開発中</p>
<!--<%= render 'form', tanuki_sad_word: @tanuki_sad_word %>-->

<%= link_to 'Back', tanuki_sad_words_path %>

app/views/tanuki_sad_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sad word:</strong>
  <%= @tanuki_sad_word.sad_word %>
</p>

<p>
  <strong>User:</strong>
  <%= @tanuki_sad_word.user_id %>
</p>

<%= link_to 'Edit', edit_tanuki_sad_word_path(@tanuki_sad_word) %> |
<%= link_to 'Back', tanuki_sad_words_path %>